import hmac
import hashlib
import uuid
import logging
from datetime import datetime, timezone
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.config import settings
from app.models.invoice import Invoice
from app.models.user import User
from app.services.portal_service import PortalService

logger = logging.getLogger("razorpay_service")

class RazorpayService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.key_id = settings.RAZORPAY_KEY_ID
        self.key_secret = settings.RAZORPAY_KEY_SECRET
        self.webhook_secret = settings.RAZORPAY_WEBHOOK_SECRET

    async def create_checkout_order(self, invoice: Invoice) -> dict:
        """
        Creates a Razorpay order for a given invoice.
        Saves the order ID into the invoice's action_metadata.
        """
        amount_paise = int(float(invoice.total_amount or invoice.amount) * 100)
        
        if not self.key_id or not self.key_secret:
            # Fallback mock order ID for testing
            mock_order_id = f"order_mock_{uuid.uuid4().hex[:12]}"
            
            metadata = dict(invoice.action_metadata or {})
            metadata["razorpay_order_id"] = mock_order_id
            invoice.action_metadata = metadata
            self.db.add(invoice)
            await self.db.commit()
            
            return {
                "id": mock_order_id,
                "amount": amount_paise,
                "currency": "INR",
                "key_id": "rzp_test_mockkeyid123",
                "mock": True
            }

        import httpx
        url = "https://api.razorpay.com/v1/orders"
        payload = {
            "amount": amount_paise,
            "currency": "INR",
            "receipt": str(invoice.id),
            "notes": {
                "invoice_id": str(invoice.id),
                "invoice_number": invoice.invoice_number
            }
        }
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(url, json=payload, auth=(self.key_id, self.key_secret))
                if response.status_code != 200:
                    logger.error(f"Razorpay order creation failed: {response.text}")
                    raise ValueError(f"Razorpay order creation failed: {response.text}")
                
                res_data = response.json()
                order_id = res_data.get("id")
                
                # Save order ID to invoice metadata
                metadata = dict(invoice.action_metadata or {})
                metadata["razorpay_order_id"] = order_id
                invoice.action_metadata = metadata
                self.db.add(invoice)
                await self.db.commit()
                
                return {
                    "id": order_id,
                    "amount": amount_paise,
                    "currency": "INR",
                    "key_id": self.key_id,
                    "mock": False
                }
        except Exception as e:
            logger.error(f"Failed to create order with Razorpay: {e}")
            raise ValueError(f"Failed to initiate checkout order: {e}")

    def verify_payment_signature(self, order_id: str, payment_id: str, signature: str) -> bool:
        """
        Verify signature generated by Razorpay Checkout modal after payment capture.
        """
        if not self.key_secret:
            # Bypass check in mock mode for test stability
            if order_id.startswith("order_mock_"):
                return True
            return False

        msg = f"{order_id}|{payment_id}".encode("utf-8")
        expected = hmac.new(self.key_secret.encode("utf-8"), msg, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, signature)

    def verify_webhook_signature(self, raw_payload: bytes, signature: str) -> bool:
        """
        Verify incoming webhook signature using RAZORPAY_WEBHOOK_SECRET.
        """
        secret = self.webhook_secret or self.key_secret
        if not secret:
            # If no secret configured, fail verification unless in test profile without secrets
            return False
            
        expected = hmac.new(secret.encode("utf-8"), raw_payload, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, signature)

    async def process_webhook(self, event_data: dict) -> bool:
        """
        Processes Razorpay webhook payload.
        Supported events:
          - payment.captured
          - order.paid
          - refund.processed
        """
        event = event_data.get("event")
        entity_payload = event_data.get("payload", {})
        
        logger.info(f"Processing Razorpay webhook event: {event}")
        
        if event in ["payment.captured", "order.paid"]:
            # Retrieve payment/order attributes
            payment_obj = entity_payload.get("payment", {}).get("entity", {})
            order_id = payment_obj.get("order_id")
            transaction_id = payment_obj.get("id")
            
            if not order_id:
                # Fallback to direct order object
                order_obj = entity_payload.get("order", {}).get("entity", {})
                order_id = order_obj.get("id")
            
            if not order_id:
                logger.warning("No order_id found in webhook payload")
                return False

            # Query invoice by order ID stashed in action_metadata
            stmt = select(Invoice).where(Invoice.payment_status == "unpaid", Invoice.is_deleted == False)
            res = await self.db.execute(stmt)
            invoices = res.scalars().all()
            target_invoice = None
            for inv in invoices:
                if inv.action_metadata and inv.action_metadata.get("razorpay_order_id") == order_id:
                    target_invoice = inv
                    break
            
            if not target_invoice:
                logger.warning(f"No invoice matching order ID {order_id} found in pending invoices")
                return False

            # Query organization user directly to act as actor
            user_stmt = select(User).where(User.organization_id == target_invoice.organization_id, User.is_deleted == False)
            user_res = await self.db.execute(user_stmt)
            active_user = user_res.scalars().first()
            actor_user_id = active_user.id if active_user else uuid.UUID(int=0)

            # Complete invoice payment
            portal_service = PortalService(self.db)
            await portal_service.pay_invoice(
                organization_id=target_invoice.organization_id,
                invoice_id=target_invoice.id,
                gateway="Razorpay",
                transaction_id=transaction_id,
                actor_user_id=actor_user_id,
                actor_name="System / Webhook"
            )
            logger.info(f"Webhook paid invoice {target_invoice.invoice_number} successfully.")
            return True

        elif event == "refund.processed":
            # Process refund event
            refund_obj = entity_payload.get("refund", {}).get("entity", {})
            payment_id = refund_obj.get("payment_id")
            
            # Find payment matching the transaction/payment ID
            # Mark invoice as refunded
            from app.models.payment import Payment
            stmt = select(Payment).where(Payment.transaction_id == payment_id)
            res = await self.db.execute(stmt)
            payment = res.scalar_one_or_none()
            
            if payment:
                stmt_inv = select(Invoice).where(Invoice.id == payment.invoice_id)
                res_inv = await self.db.execute(stmt_inv)
                invoice = res_inv.scalar_one_or_none()
                if invoice:
                    invoice.status = "Refunded"
                    invoice.payment_status = "refunded"
                    payment.status = "Refunded"
                    payment.remarks = f"Refunded via webhook. Refund ID: {refund_obj.get('id')}"
                    self.db.add_all([invoice, payment])
                    await self.db.commit()
                    logger.info(f"Refund webhook processed for invoice {invoice.invoice_number}")
                    return True
            return False

        return False
