"""add_allow_additional_seats_and_users_purchased_next

Revision ID: 08f0bd8598d6
Revises: 69fc3bc0fd21
Create Date: 2026-06-24 17:35:18.928422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f0bd8598d6'
down_revision: Union[str, Sequence[str], None] = '69fc3bc0fd21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('allow_additional_seats', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('tenant_subscriptions', sa.Column('users_purchased_next', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_subscriptions', 'users_purchased_next')
    op.drop_column('plans', 'allow_additional_seats')
    # ### end Alembic commands ###
