"""extend_plans_and_add_invoice_config

Revision ID: 0bb374d3c2a3
Revises: 38858aed88c0
Create Date: 2026-06-23 11:56:41.730851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb374d3c2a3'
down_revision: Union[str, Sequence[str], None] = '38858aed88c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('extra_user_price', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    op.add_column('plans', sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False))
    op.add_column('plans', sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), server_default='0.0', nullable=False))
    op.add_column('plans', sa.Column('plan_color', sa.String(length=50), nullable=True))
    op.add_column('plans', sa.Column('plan_badge', sa.String(length=100), nullable=True))
    op.add_column('plans', sa.Column('popular_plan', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('plans', sa.Column('recommended_plan', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('plans', sa.Column('allow_upgrade', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('plans', sa.Column('allow_downgrade', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('plans', sa.Column('allow_trial', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('plans', sa.Column('auto_renew', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('plans', sa.Column('plan_active', sa.Boolean(), server_default='true', nullable=False))

    # Conditionally create the invoice_configurations table if not already present
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'invoice_configurations' not in tables:
        op.create_table(
            'invoice_configurations',
            sa.Column('id', sa.String(length=50), nullable=False),
            sa.Column('company_logo_url', sa.String(length=500), nullable=True),
            sa.Column('company_name', sa.String(length=255), nullable=False),
            sa.Column('tagline', sa.String(length=255), nullable=True),
            sa.Column('website', sa.String(length=255), nullable=True),
            sa.Column('support_email', sa.String(length=255), nullable=True),
            sa.Column('phone_number', sa.String(length=50), nullable=True),
            sa.Column('address', sa.Text(), nullable=True),
            sa.Column('gst_number', sa.String(length=50), nullable=True),
            sa.Column('pan', sa.String(length=50), nullable=True),
            sa.Column('business_registration_number', sa.String(length=100), nullable=True),
            sa.Column('invoice_prefix', sa.String(length=50), nullable=False),
            sa.Column('starting_invoice_number', sa.Integer(), nullable=False),
            sa.Column('currency', sa.String(length=10), nullable=False),
            sa.Column('currency_symbol', sa.String(length=10), nullable=False),
            sa.Column('bank_name', sa.String(length=255), nullable=True),
            sa.Column('account_holder', sa.String(length=255), nullable=True),
            sa.Column('account_number', sa.String(length=100), nullable=True),
            sa.Column('ifsc', sa.String(length=50), nullable=True),
            sa.Column('branch', sa.String(length=255), nullable=True),
            sa.Column('upi_id', sa.String(length=255), nullable=True),
            sa.Column('qr_code_url', sa.String(length=500), nullable=True),
            sa.Column('payment_terms', sa.Text(), nullable=True),
            sa.Column('footer_text', sa.Text(), nullable=True),
            sa.Column('invoice_subject', sa.String(length=255), nullable=True),
            sa.Column('invoice_body', sa.Text(), nullable=True),
            sa.Column('reminder_subject', sa.String(length=255), nullable=True),
            sa.Column('reminder_body', sa.Text(), nullable=True),
            sa.Column('payment_success_subject', sa.String(length=255), nullable=True),
            sa.Column('payment_success_body', sa.Text(), nullable=True),
            sa.Column('payment_failed_subject', sa.String(length=255), nullable=True),
            sa.Column('payment_failed_body', sa.Text(), nullable=True),
            sa.Column('renewal_reminder_subject', sa.String(length=255), nullable=True),
            sa.Column('renewal_reminder_body', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_configurations')
    op.drop_column('plans', 'plan_active')
    op.drop_column('plans', 'auto_renew')
    op.drop_column('plans', 'allow_trial')
    op.drop_column('plans', 'allow_downgrade')
    op.drop_column('plans', 'allow_upgrade')
    op.drop_column('plans', 'recommended_plan')
    op.drop_column('plans', 'popular_plan')
    op.drop_column('plans', 'plan_badge')
    op.drop_column('plans', 'plan_color')
    op.drop_column('plans', 'gst_percentage')
    op.drop_column('plans', 'discount_percentage')
    op.drop_column('plans', 'extra_user_price')
    # ### end Alembic commands ###
