"""add_extra_storage_gb_to_organizations

Revision ID: 668c3962677d
Revises: b420c72ae938
Create Date: 2026-06-24 03:06:38.745813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668c3962677d'
down_revision: Union[str, Sequence[str], None] = 'b420c72ae938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('extra_storage_gb', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'extra_storage_gb')
    # ### end Alembic commands ###
