"""add_seat_licensing_fields_and_phone

Revision ID: 69fc3bc0fd21
Revises: b10510723214
Create Date: 2026-06-24 15:41:57.952035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69fc3bc0fd21'
down_revision: Union[str, Sequence[str], None] = 'b10510723214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seat_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('inactive_reason', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_seat_number'), 'users', ['seat_number'], unique=False)
    # ### end Alembic commands ###

    # Backfill seat numbers for existing non-deleted users grouped by organization
    op.execute("""
        WITH numbered_users AS (
            SELECT id, organization_id,
                   ROW_NUMBER() OVER (PARTITION BY organization_id ORDER BY created_at ASC) as row_num
            FROM users
            WHERE is_deleted = false
        )
        UPDATE users
        SET seat_number = 'Seat-' || LPAD(numbered_users.row_num::text, 3, '0')
        FROM numbered_users
        WHERE users.id = numbered_users.id;
    """)

    # Insert initial "Assigned" history records in the seat_assignment_history table
    op.execute("""
        INSERT INTO seat_assignment_history (id, organization_id, seat_number, user_id, action, created_at, updated_at, is_deleted)
        SELECT 
            gen_random_uuid(),
            organization_id,
            seat_number,
            id,
            'Assigned',
            NOW(),
            NOW(),
            false
        FROM users
        WHERE seat_number IS NOT NULL AND is_deleted = false;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_seat_number'), table_name='users')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'inactive_reason')
    op.drop_column('users', 'seat_number')
    # ### end Alembic commands ###
