"""add_action_metadata_to_invoices

Revision ID: 9612c02a15d9
Revises: 668c3962677d
Create Date: 2026-06-24 03:14:34.409506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9612c02a15d9'
down_revision: Union[str, Sequence[str], None] = '668c3962677d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('action_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'action_metadata')
    # ### end Alembic commands ###
