"""create_sales_ops_tables

Revision ID: a24276f45d48
Revises: fe7554e40f40
Create Date: 2026-06-04 04:44:51.812473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24276f45d48'
down_revision: Union[str, Sequence[str], None] = 'fe7554e40f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_configs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_configs_organization_id'), 'assignment_configs', ['organization_id'], unique=True)
    op.create_table('lead_imports',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('mapping_confidence', sa.Float(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('failed_rows_csv', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_imports_organization_id'), 'lead_imports', ['organization_id'], unique=False)
    op.add_column('leads', sa.Column('import_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_leads_import_id'), 'leads', ['import_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'lead_imports', ['import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_import_id'), table_name='leads')
    op.drop_column('leads', 'import_id')
    op.drop_index(op.f('ix_lead_imports_organization_id'), table_name='lead_imports')
    op.drop_table('lead_imports')
    op.drop_index(op.f('ix_assignment_configs_organization_id'), table_name='assignment_configs')
    op.drop_table('assignment_configs')
    # ### end Alembic commands ###
