"""add_org_portal_fields_and_support_tickets

Revision ID: b420c72ae938
Revises: 68d645146689
Create Date: 2026-06-23 18:03:50.497199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b420c72ae938'
down_revision: Union[str, Sequence[str], None] = '68d645146689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.add_column('organizations', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('support_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('support_phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), nullable=False, server_default='Asia/Kolkata'))
    op.add_column('organizations', sa.Column('language', sa.String(length=50), nullable=False, server_default='English'))
    op.add_column('organizations', sa.Column('currency', sa.String(length=10), nullable=False, server_default='INR'))
    op.add_column('organizations', sa.Column('billing_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('pan', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('billing_address', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('billing_city', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('billing_state', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('billing_country', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('billing_pin_code', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('billing_phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('notification_invoice_emails', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('organizations', sa.Column('notification_renewal_emails', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('organizations', sa.Column('notification_support_emails', sa.Boolean(), nullable=False, server_default='true'))

    # Check if support_tickets table is already created to prevent conflicts during seeding/migration bootstrap
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'support_tickets' not in tables:
        op.create_table(
            'support_tickets',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('organization_id', sa.UUID(), nullable=False),
            sa.Column('created_by_id', sa.UUID(), nullable=False),
            sa.Column('subject', sa.String(length=255), nullable=False),
            sa.Column('priority', sa.String(length=50), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('attachments', sa.JSON(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('assigned_to_id', sa.UUID(), nullable=True),
            sa.Column('resolution', sa.Text(), nullable=True),
            sa.Column('comments', sa.JSON(), nullable=True),
            sa.Column('history', sa.JSON(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('is_deleted', sa.Boolean(), nullable=False),
            sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_support_tickets_organization_id'), 'support_tickets', ['organization_id'], unique=False)
        op.create_index(op.f('ix_support_tickets_created_by_id'), 'support_tickets', ['created_by_id'], unique=False)
        op.create_index(op.f('ix_support_tickets_assigned_to_id'), 'support_tickets', ['assigned_to_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_assigned_to_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_created_by_id'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_organization_id'), table_name='support_tickets')
    op.drop_table('support_tickets')

    op.drop_column('organizations', 'notification_support_emails')
    op.drop_column('organizations', 'notification_renewal_emails')
    op.drop_column('organizations', 'notification_invoice_emails')
    op.drop_column('organizations', 'billing_phone')
    op.drop_column('organizations', 'billing_email')
    op.drop_column('organizations', 'billing_pin_code')
    op.drop_column('organizations', 'billing_country')
    op.drop_column('organizations', 'billing_state')
    op.drop_column('organizations', 'billing_city')
    op.drop_column('organizations', 'billing_address')
    op.drop_column('organizations', 'pan')
    op.drop_column('organizations', 'gst_number')
    op.drop_column('organizations', 'billing_name')
    op.drop_column('organizations', 'currency')
    op.drop_column('organizations', 'language')
    op.drop_column('organizations', 'timezone')
    op.drop_column('organizations', 'support_phone')
    op.drop_column('organizations', 'support_email')
    op.drop_column('organizations', 'website')
    op.drop_column('organizations', 'logo_url')
    # ### end Alembic commands ###
