"""add_call_fields_to_activities

Revision ID: 1fd6450720c7
Revises: 241f06824057
Create Date: 2026-06-23 07:39:15.544648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd6450720c7'
down_revision: Union[str, Sequence[str], None] = '241f06824057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('call_sid', sa.String(length=100), nullable=True))
    op.add_column('activities', sa.Column('recording_url', sa.String(length=512), nullable=True))
    op.add_column('activities', sa.Column('call_duration', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('call_direction', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_activities_call_sid'), 'activities', ['call_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_call_sid'), table_name='activities')
    op.drop_column('activities', 'call_direction')
    op.drop_column('activities', 'call_duration')
    op.drop_column('activities', 'recording_url')
    op.drop_column('activities', 'call_sid')
    # ### end Alembic commands ###
