"""create_subscription_billing_tables

Revision ID: 241f06824057
Revises: d7c2d95b993f
Create Date: 2026-06-22 13:06:31.197950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241f06824057'
down_revision: Union[str, Sequence[str], None] = 'd7c2d95b993f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'plans',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('price_inr', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('billing_cycle_days', sa.Integer(), nullable=False),
        sa.Column('max_users', sa.Integer(), nullable=False),
        sa.Column('max_admins', sa.Integer(), nullable=False),
        sa.Column('max_managers', sa.Integer(), nullable=False),
        sa.Column('max_team_leads', sa.Integer(), nullable=False),
        sa.Column('max_employees', sa.Integer(), nullable=False),
        sa.Column('features', sa.JSON(), nullable=False),
        sa.Column('is_trial', sa.Boolean(), nullable=False),
        sa.Column('trial_days', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)

    op.create_table(
        'tenant_subscriptions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('plan_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('trial_end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('auto_renew', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_subscriptions_organization_id'), 'tenant_subscriptions', ['organization_id'], unique=True)
    op.create_index(op.f('ix_tenant_subscriptions_plan_id'), 'tenant_subscriptions', ['plan_id'], unique=False)

    op.add_column('invoices', sa.Column('plan_name', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('invoices', sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('invoices', sa.Column('payment_status', sa.String(length=50), nullable=False))
    op.alter_column('organizations', 'subscription_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'reset_token_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expires',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('organizations', 'subscription_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('invoices', 'payment_status')
    op.drop_column('invoices', 'issue_date')
    op.drop_column('invoices', 'currency')
    op.drop_column('invoices', 'amount_inr')
    op.drop_column('invoices', 'plan_name')
    
    op.drop_index(op.f('ix_tenant_subscriptions_plan_id'), table_name='tenant_subscriptions')
    op.drop_index(op.f('ix_tenant_subscriptions_organization_id'), table_name='tenant_subscriptions')
    op.drop_table('tenant_subscriptions')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
