"""add_billing_and_metrics_to_subscriptions

Revision ID: 38858aed88c0
Revises: 1fd6450720c7
Create Date: 2026-06-23 11:26:31.487535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38858aed88c0'
down_revision: Union[str, Sequence[str], None] = '1fd6450720c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subscription_id', sa.Uuid(), nullable=True))
    op.add_column('invoices', sa.Column('setup_charges', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('extra_users_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('gst_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('pdf_file_path', sa.String(length=512), nullable=True))
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'tenant_subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.add_column('plans', sa.Column('display_name', sa.String(length=150), nullable=False))
    op.add_column('plans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('plans', sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('quarterly_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('annual_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('plans', sa.Column('storage_limit_gb', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('recording_retention_days', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('priority_support', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('api_access', sa.Boolean(), nullable=False))
    op.add_column('plans', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('setup_charges', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('plans', sa.Column('minimum_users', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('maximum_users', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('minimum_contract_months', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('promo_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('plans', sa.Column('promo_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('plans', sa.Column('promo_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('billing_cycle', sa.String(length=20), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('next_invoice_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('renewal_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tenant_subscriptions', sa.Column('users_purchased', sa.Integer(), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('users_active', sa.Integer(), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('storage_used', sa.Numeric(precision=10, scale=3), nullable=False))
    op.add_column('tenant_subscriptions', sa.Column('call_recording_usage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_subscriptions', 'call_recording_usage')
    op.drop_column('tenant_subscriptions', 'storage_used')
    op.drop_column('tenant_subscriptions', 'users_active')
    op.drop_column('tenant_subscriptions', 'users_purchased')
    op.drop_column('tenant_subscriptions', 'renewal_date')
    op.drop_column('tenant_subscriptions', 'next_invoice_date')
    op.drop_column('tenant_subscriptions', 'billing_cycle')
    op.drop_column('plans', 'promo_end_date')
    op.drop_column('plans', 'promo_start_date')
    op.drop_column('plans', 'promo_price')
    op.drop_column('plans', 'minimum_contract_months')
    op.drop_column('plans', 'maximum_users')
    op.drop_column('plans', 'minimum_users')
    op.drop_column('plans', 'setup_charges')
    op.drop_column('plans', 'display_order')
    op.drop_column('plans', 'api_access')
    op.drop_column('plans', 'priority_support')
    op.drop_column('plans', 'recording_retention_days')
    op.drop_column('plans', 'storage_limit_gb')
    op.drop_column('plans', 'currency')
    op.drop_column('plans', 'annual_price')
    op.drop_column('plans', 'quarterly_price')
    op.drop_column('plans', 'monthly_price')
    op.drop_column('plans', 'description')
    op.drop_column('plans', 'display_name')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_column('invoices', 'pdf_file_path')
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'gst_amount')
    op.drop_column('invoices', 'discount_amount')
    op.drop_column('invoices', 'extra_users_amount')
    op.drop_column('invoices', 'setup_charges')
    op.drop_column('invoices', 'subscription_id')
    # ### end Alembic commands ###
