"""add_lead_city_and_indexes

Revision ID: 8ea2be2b2d8b
Revises: 229a8389baf8
Create Date: 2026-06-21 11:47:37.548853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea2be2b2d8b'
down_revision: Union[str, Sequence[str], None] = '229a8389baf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_leads_city'), 'leads', ['city'], unique=False)
    op.create_index(op.f('ix_leads_first_name'), 'leads', ['first_name'], unique=False)
    op.create_index(op.f('ix_leads_last_name'), 'leads', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_last_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_first_name'), table_name='leads')
    op.drop_index(op.f('ix_leads_city'), table_name='leads')
    op.drop_column('leads', 'city')
    # ### end Alembic commands ###
