"""add_org_renewal_theme_and_ticket_fields

Revision ID: a2522363289b
Revises: 9612c02a15d9
Create Date: 2026-06-24 03:58:40.594934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2522363289b'
down_revision: Union[str, Sequence[str], None] = '9612c02a15d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('auto_renewal', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('organizations', sa.Column('theme', sa.String(length=50), server_default='dark', nullable=False))
    op.add_column('support_tickets', sa.Column('ticket_number', sa.String(length=100), nullable=False))
    op.add_column('support_tickets', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('support_tickets', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_column('support_tickets', 'closed_at')
    op.drop_column('support_tickets', 'resolved_at')
    op.drop_column('support_tickets', 'ticket_number')
    op.drop_column('organizations', 'theme')
    op.drop_column('organizations', 'auto_renewal')
    # ### end Alembic commands ###
