"""add_missing_foreign_key_indexes

Revision ID: b10510723214
Revises: a2522363289b
Create Date: 2026-06-24 10:39:32.761311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10510723214'
down_revision: Union[str, Sequence[str], None] = 'a2522363289b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_activities_created_by'), 'activities', ['created_by'], unique=False)
    op.create_index(op.f('ix_assignment_configs_last_assigned_user_id'), 'assignment_configs', ['last_assigned_user_id'], unique=False)
    op.create_index(op.f('ix_companies_created_by'), 'companies', ['created_by'], unique=False)
    op.create_index(op.f('ix_contacts_created_by'), 'contacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_lead_imports_created_by'), 'lead_imports', ['created_by'], unique=False)
    op.create_index(op.f('ix_leads_created_by'), 'leads', ['created_by'], unique=False)
    op.create_index(op.f('ix_notes_created_by'), 'notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_invitations_created_by'), 'user_invitations', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_invitations_created_by'), table_name='user_invitations')
    op.drop_index(op.f('ix_notes_created_by'), table_name='notes')
    op.drop_index(op.f('ix_leads_created_by'), table_name='leads')
    op.drop_index(op.f('ix_lead_imports_created_by'), table_name='lead_imports')
    op.drop_index(op.f('ix_contacts_created_by'), table_name='contacts')
    op.drop_index(op.f('ix_companies_created_by'), table_name='companies')
    op.drop_index(op.f('ix_assignment_configs_last_assigned_user_id'), table_name='assignment_configs')
    op.drop_index(op.f('ix_activities_created_by'), table_name='activities')
    # ### end Alembic commands ###
