"""whatsapp_integration_v2

Revision ID: d4ed228a0455
Revises: metadata_version_0001
Create Date: 2026-08-06 04:44:01.851865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ed228a0455'
down_revision: Union[str, Sequence[str], None] = 'metadata_version_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_contacts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'phone', name='uq_whatsapp_contact_org_phone')
    )
    op.create_index(op.f('ix_whatsapp_contacts_organization_id'), 'whatsapp_contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_contacts_phone'), 'whatsapp_contacts', ['phone'], unique=False)
    op.create_table('whatsapp_labels',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_whatsapp_label_org_name')
    )
    op.create_index(op.f('ix_whatsapp_labels_organization_id'), 'whatsapp_labels', ['organization_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('meta_template_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('header_format', sa.String(length=20), nullable=True),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', 'language', name='uq_whatsapp_template_org_name_lang')
    )
    op.create_index(op.f('ix_whatsapp_templates_language'), 'whatsapp_templates', ['language'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_meta_template_id'), 'whatsapp_templates', ['meta_template_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_name'), 'whatsapp_templates', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_organization_id'), 'whatsapp_templates', ['organization_id'], unique=False)
    op.create_table('whatsapp_webhook_events',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_webhook_events_event_id'), 'whatsapp_webhook_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_whatsapp_webhook_events_event_type'), 'whatsapp_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_webhook_events_organization_id'), 'whatsapp_webhook_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_webhook_events_status'), 'whatsapp_webhook_events', ['status'], unique=False)
    op.create_table('whatsapp_conversation_labels',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['whatsapp_labels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'label_id')
    )
    op.create_index(op.f('ix_whatsapp_conversation_labels_conversation_id'), 'whatsapp_conversation_labels', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversation_labels_label_id'), 'whatsapp_conversation_labels', ['label_id'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('wa_status', sa.String(length=20), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_sentiment', sa.String(length=30), nullable=True),
    sa.Column('ai_intent', sa.String(length=50), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['whatsapp_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_conversation_id'), 'whatsapp_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_is_internal'), 'whatsapp_messages', ['is_internal'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_organization_id'), 'whatsapp_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wa_message_id'), 'whatsapp_messages', ['wa_message_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_wa_status'), 'whatsapp_messages', ['wa_status'], unique=False)
    op.create_table('whatsapp_attachments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('media_id', sa.String(length=64), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['whatsapp_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_attachments_media_id'), 'whatsapp_attachments', ['media_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_attachments_message_id'), 'whatsapp_attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_attachments_organization_id'), 'whatsapp_attachments', ['organization_id'], unique=False)
    op.add_column('whatsapp_conversations', sa.Column('whatsapp_settings_id', sa.Uuid(), nullable=False))
    op.add_column('whatsapp_conversations', sa.Column('whatsapp_contact_id', sa.Uuid(), nullable=True))
    op.add_column('whatsapp_conversations', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.add_column('whatsapp_conversations', sa.Column('sla_status', sa.String(length=20), nullable=False))
    op.add_column('whatsapp_conversations', sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_conversations', sa.Column('response_time_sum', sa.Integer(), nullable=False))
    op.add_column('whatsapp_conversations', sa.Column('response_count', sa.Integer(), nullable=False))
    op.add_column('whatsapp_conversations', sa.Column('locked_by_user_id', sa.Uuid(), nullable=True))
    op.add_column('whatsapp_conversations', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_conversations', sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_whatsapp_conversation_org_phone'), 'whatsapp_conversations', type_='unique')
    op.create_index(op.f('ix_whatsapp_conversations_is_pinned'), 'whatsapp_conversations', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_sla_due_at'), 'whatsapp_conversations', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_sla_status'), 'whatsapp_conversations', ['sla_status'], unique=False)
    op.create_index(op.f('ix_whatsapp_conversations_whatsapp_settings_id'), 'whatsapp_conversations', ['whatsapp_settings_id'], unique=False)
    op.create_unique_constraint('uq_whatsapp_conversation_org_phone_settings', 'whatsapp_conversations', ['organization_id', 'phone', 'whatsapp_settings_id'])
    op.create_foreign_key(None, 'whatsapp_conversations', 'users', ['locked_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'whatsapp_conversations', 'whatsapp_contacts', ['whatsapp_contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'whatsapp_conversations', 'whatsapp_settings', ['whatsapp_settings_id'], ['id'], ondelete='CASCADE')
    op.add_column('whatsapp_settings', sa.Column('meta_app_id', sa.String(length=64), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('webhook_secret_enc', sa.Text(), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('webhook_url', sa.String(length=255), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('api_version', sa.String(length=20), nullable=False))
    op.add_column('whatsapp_settings', sa.Column('default_country_code', sa.String(length=10), nullable=False))
    op.add_column('whatsapp_settings', sa.Column('health_status', sa.String(length=24), nullable=False))
    op.drop_constraint(op.f('uq_whatsapp_settings_organization'), 'whatsapp_settings', type_='unique')
    op.create_index(op.f('ix_whatsapp_settings_phone_number_id'), 'whatsapp_settings', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_settings_sender_number'), 'whatsapp_settings', ['sender_number'], unique=False)
    op.create_unique_constraint('uq_whatsapp_settings_org_phone', 'whatsapp_settings', ['organization_id', 'phone_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_whatsapp_settings_org_phone', 'whatsapp_settings', type_='unique')
    op.drop_index(op.f('ix_whatsapp_settings_sender_number'), table_name='whatsapp_settings')
    op.drop_index(op.f('ix_whatsapp_settings_phone_number_id'), table_name='whatsapp_settings')
    op.create_unique_constraint(op.f('uq_whatsapp_settings_organization'), 'whatsapp_settings', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('whatsapp_settings', 'health_status')
    op.drop_column('whatsapp_settings', 'default_country_code')
    op.drop_column('whatsapp_settings', 'api_version')
    op.drop_column('whatsapp_settings', 'webhook_url')
    op.drop_column('whatsapp_settings', 'webhook_secret_enc')
    op.drop_column('whatsapp_settings', 'meta_app_id')
    op.drop_constraint(None, 'whatsapp_conversations', type_='foreignkey')
    op.drop_constraint(None, 'whatsapp_conversations', type_='foreignkey')
    op.drop_constraint(None, 'whatsapp_conversations', type_='foreignkey')
    op.drop_constraint('uq_whatsapp_conversation_org_phone_settings', 'whatsapp_conversations', type_='unique')
    op.drop_index(op.f('ix_whatsapp_conversations_whatsapp_settings_id'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_sla_status'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_sla_due_at'), table_name='whatsapp_conversations')
    op.drop_index(op.f('ix_whatsapp_conversations_is_pinned'), table_name='whatsapp_conversations')
    op.create_unique_constraint(op.f('uq_whatsapp_conversation_org_phone'), 'whatsapp_conversations', ['organization_id', 'phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('whatsapp_conversations', 'lock_expires_at')
    op.drop_column('whatsapp_conversations', 'locked_at')
    op.drop_column('whatsapp_conversations', 'locked_by_user_id')
    op.drop_column('whatsapp_conversations', 'response_count')
    op.drop_column('whatsapp_conversations', 'response_time_sum')
    op.drop_column('whatsapp_conversations', 'sla_due_at')
    op.drop_column('whatsapp_conversations', 'sla_status')
    op.drop_column('whatsapp_conversations', 'is_pinned')
    op.drop_column('whatsapp_conversations', 'whatsapp_contact_id')
    op.drop_column('whatsapp_conversations', 'whatsapp_settings_id')
    op.drop_index(op.f('ix_whatsapp_attachments_organization_id'), table_name='whatsapp_attachments')
    op.drop_index(op.f('ix_whatsapp_attachments_message_id'), table_name='whatsapp_attachments')
    op.drop_index(op.f('ix_whatsapp_attachments_media_id'), table_name='whatsapp_attachments')
    op.drop_table('whatsapp_attachments')
    op.drop_index(op.f('ix_whatsapp_messages_wa_status'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_wa_message_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_organization_id'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_is_internal'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_conversation_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_conversation_labels_label_id'), table_name='whatsapp_conversation_labels')
    op.drop_index(op.f('ix_whatsapp_conversation_labels_conversation_id'), table_name='whatsapp_conversation_labels')
    op.drop_table('whatsapp_conversation_labels')
    op.drop_index(op.f('ix_whatsapp_webhook_events_status'), table_name='whatsapp_webhook_events')
    op.drop_index(op.f('ix_whatsapp_webhook_events_organization_id'), table_name='whatsapp_webhook_events')
    op.drop_index(op.f('ix_whatsapp_webhook_events_event_type'), table_name='whatsapp_webhook_events')
    op.drop_index(op.f('ix_whatsapp_webhook_events_event_id'), table_name='whatsapp_webhook_events')
    op.drop_table('whatsapp_webhook_events')
    op.drop_index(op.f('ix_whatsapp_templates_organization_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_name'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_meta_template_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_language'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_labels_organization_id'), table_name='whatsapp_labels')
    op.drop_table('whatsapp_labels')
    op.drop_index(op.f('ix_whatsapp_contacts_phone'), table_name='whatsapp_contacts')
    op.drop_index(op.f('ix_whatsapp_contacts_organization_id'), table_name='whatsapp_contacts')
    op.drop_table('whatsapp_contacts')
    # ### end Alembic commands ###
