"""add_whatsapp_settings_metadata_and_default_fields

Revision ID: e03485c55747
Revises: d4ed228a0455
Create Date: 2026-08-06 05:08:18.894252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03485c55747'
down_revision: Union[str, Sequence[str], None] = 'd4ed228a0455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_settings', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('whatsapp_settings', sa.Column('quality_rating', sa.String(length=30), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('messaging_limit', sa.String(length=50), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('display_name_status', sa.String(length=50), nullable=True))
    op.add_column('whatsapp_settings', sa.Column('capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_settings', 'capabilities')
    op.drop_column('whatsapp_settings', 'display_name_status')
    op.drop_column('whatsapp_settings', 'messaging_limit')
    op.drop_column('whatsapp_settings', 'quality_rating')
    op.drop_column('whatsapp_settings', 'is_default')
    # ### end Alembic commands ###
